---
# Install and config dehydrated and all challenge hooks

- name: "SETUP : install and config ACME client dehydrated:"
  include: "setup_dehydrated.yml"

- name: "SETUP : install and config dns provider hook(s) for dns-01 challenge:"
  include: "setup_{{ le_setup_dns_loop }}.yml"
  static: no
  with_items:
    - "{{ le_dns_providers }}"
  loop_control:
    loop_var: le_setup_dns_loop

- name: "SETUP : config proxy- or/and webserver for http-01 challenge:"
  include: "setup_{{ le_http_webserver }}.yml"
  static: no
  when:
    - le_http_webserver is defined
    - le_http_webserver != ""
    - le_http_webserver is not none
